modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="storyengine"
version="2.0.0"
displayName="StoryEngine"
description="Движок сюжетов для Minecraft"
authors="StoryEngine Team (GidexPlayYT)"

[[dependencies.storyengine]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.storyengine]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"